config/routes.rb
Rails.application.routes.draw do
  get 'users', to: 'users#index'
  get 'users/login', to: 'users#login'
  post 'users/login', to: 'users#create'
  get 'users/registration', to: 'users#registration'
  get 'index', to: 'welcome#index'
  root 'tasks#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resource :session
  resources :tasks
  resource :profile
  post 'profile/share', to: 'profiles#share', as: :share
  patch 'profile/save_image', to: 'profiles#save_image', as: :save_image
  get '/friends/:friend_id/tasks', to: 'shared_tasks#index', as: :friend_tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/owner_to_friend.rb
class OwnerToFriend < ApplicationRecord
  belongs_to :owner, class_name: 'User', foreign_key: 'owner_id'
  belongs_to :friend, class_name: 'User', foreign_key: 'friend_id'
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :description, presence: true
  validates_length_of :description, minimum: 5
  validates :expire_at, inclusion: { in: (Date.today..Date.today+5.years) }
  enum status: %i[todo done]

  scope :q, ->(q) { where("title LIKE '%#{q}%'") if q.present? }
  scope :s, ->(s) { where(status: s) if s && s != "all statuses" }
  scope :d, ->(d) { where(expire_at: d) if d.present? }

  scope :f, ->(f) do
    if f == "expired"
      where("expire_at < ?", Date.today)
    elsif f == "not expired"
      where("expire_at >= ?", Date.today)
    end
  end

  scope :sorting, ->(sorting) do
    if sorting == "expire at asc"
       order(expire_at: :asc)
    elsif sorting == "expire at desc"
      order(expire_at: :desc)
    elsif sorting == "title asc"
      order(title: :asc)
    elsif sorting == "title desc"
      order(title: :desc)
    end
  end
  
  scope :for_dashboard, ->(params) do
     q(params[:q]).s(params[:s])
     .d(params[:d])
     .f(params[:f])
     .sorting(params[:sorting])
     .paginate(page: params[:page], per_page: 5) 
  end

  def done?
    status == "done"
  end

  alias done done?

  def done=(value)
    if value == '1'
      self.status = 1
    else
      self.status = 0
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, uniqueness: true, length: { minimum: 3 }
  validates_length_of :password, minimum: 6, allow_blank: true

  has_secure_password validations: false

  has_many :tasks

  has_many :owner_users, class_name: 'OwnerToFriend', primary_key: 'id', foreign_key: 'owner_id'
  has_many :owner_friends, class_name: 'OwnerToFriend', primary_key: 'id', foreign_key: 'friend_id'

  has_many :owners, through: :owner_friends
  has_many :friends, through: :owner_users

  	
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :user_signed_in?

  def require_user
    redirect_to new_session_path unless current_user
  end
  
  #def require_guest
    #redirect_to tasks_path if current_user
  #end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def user_signed_in?
    !current_user.nil?
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :require_user

  def show  
    @friends_i_share = current_user.friends
    @friends_share_me = current_user.owners
    #@friends_i_share = OwnerToFriend.where(owner_id: current_user.id).map(&:friend)
    #@friends_share_me = OwnerToFriend.where(friend_id: current_user.id).map(&:owner)
  end

  def update 
  end

  def share
    @friend = User.find_by(name: params[:friend])
    if @friend.nil?
     redirect_to profile_path 
    else
      if allowed_sharing?
        OwnerToFriend.create(friend_id: @friend.id, owner_id: current_user.id)    
      end
    redirect_to profile_path
    end
  end

  def destroy
    OwnerToFriend.where(friend_id: params[:friend_id]).delete_all
    redirect_to profile_path
  end

  def allowed_sharing?
     us = OwnerToFriend.find_by(owner_id: current_user.id, friend_id: @friend.id)
     us.nil?
  end

  def save_image
    current_user.image = params[:user][:image]
    current_user.save

    redirect_to profile_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.find_by(name: user_params[:name])
    @user ||= User.create(user_params)
    if @user.valid? && @user.authenticate(user_params[:password])
      session[:user_id] = @user.id
      redirect_to tasks_path
      UserMailer.with(user: @user).logged_in_email.deliver_later
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to new_session_path
  end

  private
  def user_params
    params.require(:user).permit(:name, :password, :email, :image)
  end
end

app/controllers/shared_tasks_controller.rb
class SharedTasksController < ApplicationController
  before_action :require_user
  before_action :require_friend

  def index
    @tasks = Task.for_dashboard(params).where(user_id: params[:friend_id])
  end

  def require_friend
    redirect_to profile_path unless friend?
  end

  def friend?
    OwnerToFriend.where(friend_id: current_user.id, owner_id: params[:friend_id]).exists?
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :require_user


  def index
    @task = Task.new
    @tasks = Task.for_dashboard(params).where(user_id: params[:user_id] || current_user)
  end

  def create
    @task = current_user.tasks.create(task_params)
    return if @task.invalid?
    @task.save
    redirect_to :root
  end

  def update
    task.update(task_params)
    head 200
  end

  def destroy
    Task.delete(params[:id])
    redirect_to :root
  end

  private

  def task
    @task ||= current_user.tasks.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :status, :done, :description, :expire_at )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lesson4</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%=javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <!--  
      <script src="//code.jquery.com/jquery-1.11.2.min.js"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  -->
 
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  </head>

  <body>
  <nav class="navbar navbar-dark bg-dark">
  <% if user_signed_in? %>    
    <%= current_user.name %> 
    <div class="right">
      <%= link_to('My tasks list', tasks_path)%> 
      |
      <%= link_to('My profile', profile_path)%> 
      |
      <%= link_to('Logout', session_path , method: :delete)%> 
    </div>
  <%else%>
    <div class="center">
     <h5>Sign up to create your own task list</h5>
    </div>
  <%end%>
      </nav>
  <div class="container">
    <%= yield %>
  </div>

  </body>
</html>

app/views/profiles/show.erb
<div class="container">
  <h3> My profile </h3> 
  <div class="row">
    <div class="col-sm-8">
      <%= image_tag(current_user.image.thumb.url,  alt: 'Image') if current_user.image? %>
      <%= form_for current_user, url: save_image_path, method: :patch do |f| %>
        <div class="profile_foto">
          <%= f.label :image %>
          <%= f.file_field :image, value: current_user.image %>
          <%= f.button :Save %>
        </div>
      <% end %> 
      <p> <%= current_user.name%> </p>
      <p><%= current_user.email%></p>
    </div>
    <div class="col-sm-4">      
      <section class="profile-container">
           <%= form_tag share_path, method: :post do |f| %>
            <div class="profile_f">
              <%= text_field_tag :friend, params[:friend], class: 'search', placeholder: "Enter user name" %>
              <%= submit_tag "Share", class: "btn btn-outline-success btn-sm", id: "profile_add_btn" %>
            </div>
          <% end %>     
      </section> 
      <ul>Shared to:
      <% @friends_i_share.each do |friend|%>
        <li>
          <%= friend.name %>
          <%= link_to '&cross;'.html_safe, profile_path(friend_id: friend.id), method: :delete, :remote => true %> 
        </li>
      <%end%>
      </ul>
      <ul>Shared to me:
      <% @friends_share_me.each do |friend|%>
        <li><a href="<%=friend_tasks_path(friend_id: friend.id)%>"><%= friend.name %></a></li>
      <%end%>
    </ul>
      </div>
  </div>
 
</div>

app/views/shared_tasks/index.erb
<div class="col-sm-10">
    <section class="tasks-container">
        <%= form_tag tasks_path, method: :get do |f| %>
          <div class="search_fm">
            <%= text_field_tag :q, params[:q], class: 'search' %>
            <%= select_tag :s, options_for_select([ "all statuses", "todo", "done"], params[:s] || "all statuses"), class: "search_sel"%>
            <%= select_tag :f, options_for_select([ "all dates", "expired", "not expired"], params[:f] || "all dates"), class: "search_sel"%>
            <%= date_field_tag :d, params[:d], id:"date_search"%>
            <%= select_tag :sorting, options_for_select([ "sorting none", "expire at asc", "expire at desc", "title asc", "title desc"],
                 params[:sorting] || "sorting none"), class: "search_sel"%>
            <%= submit_tag "Search", class: "btn btn-outline-success btn-sm", id: "search_btn" %>
          </div>
      <% end %>
    </section>
  </div>
</div>
<div id="task">
  <h2>Tasks</h2>
    <%= render partial: 'tasks/task', collection: @tasks %>
</div>
<div id="pages">
  <%= will_paginate @tasks %>
</div>

app/views/tasks/_form.html.erb
<button type="button" id="create_md_btn" class="btn btn-success btn-lg" data-toggle="modal" data-target="#modalCreate">
  New task
</button>
<div  id="modalCreate" class="modal fade" role="dialog">
  <div class="modal-dialog" >
   <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Create task</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
    <div class="modal-body">
        <%= form_for @task, remote: true do |f| %>
          <div class="input-group input-group-sm mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text" id="inputGroup-sizing-sm">Title</span>
            </div>
            <%= f.text_field :title, value: @task.title, class: 'form-control', 'aria-label' => 'Small', 'aria-describedby' => 'inputGroup-sizing-sm'%>
            <%= @task.errors[:title].first %>
          </div>
          <div class="form-group">
            <label for="exampleFormControlTextarea1">Description</label>
            <%= f.text_area :description, value: @task.description, id: 'exampleFormControlTextarea1', class: 'form-control', rows: 3 %>
            <%= @task.errors[:description].first %>
          </div>
          <%= f.date_field :expire_at, value: @task.expire_at %>
            <%= @task.errors[:expire_at].first %>
          <%= f.button :Save %>
        <% end %>
        <% if notice %>
          <div class="error-container alert alert-danger" role="alert">
            <% notice.each do |error_message| %>
              <p><%= "Field #{error_message.first} #{error_message[1].first}" %></p>
            <% end %>
          </div>
        <% end %>
    </div>
    </div>
  </div>
</div>

app/views/tasks/_task.html.erb
 <!--<li class="task-item alert <%= task.status.to_i.zero? ? 'alert-secondary' : 'alert-success'%>" role="alert">
  
  <p class="task-title" title="<%= task.description %>"><%= task.title %></p>
  <div class="buttons-container">
    <%= button_tag 'X', 'data-url' => task_path(task), 'data-remote' => true, 'data-method' => :delete, class: "btn #{task.status.to_i.zero? ? 'btn-dark' : 'btn-success'}"%>
    <%= form_for task, remote: true do |f| %>
      <%= f.check_box :status, checked: task.done?, onchange: "this.setAttribute('data-params', 'task[status]=' + (this.checked ? 'done' : 'todo'))", data: {url: task_path(task), remote: true, method: :patch} %>
    <% end %>
    -->

  <%= form_for task, remote: true do |f| %>
    <div class="form-row">
      <div class="form-group col-md-5 "> 
          <%= f.text_field :title, class: "task_text form-control new_task", 
           placeholder: task.title , autocomplete: "off", required: true %>
      </div>
      
      <div class="form-group col-md-3"> 
        <%= f.date_field :expire_at, id:"date", min: Date.today.strftime("%F "), required: true%>
      </div>
      <div class="form-group col-md-1"> 
        <%= link_to '&cross;'.html_safe, task, id:"delete", method: :delete, :remote => true %>
      </div> 
      <div class="form-group col-md-1"> 
        <%= f.check_box :done, class:"task_checkbox"  %>
      </div>
      <div class="form-group col-md-2">
        <%= f.submit "Save", class: "btn btn-success btn-sm" %>
      </div>
    <div class="form-group col-md-12 h0"> 
      <%= f.text_area :description, minlength:5%> 
    </div>       
    
  </div>
 <% end %>

app/views/tasks/create.js.erb
document.getElementById('new_task').innerHTML = "<%= j(render 'form') %>"

app/views/tasks/index.html.erb
<div class="row">
  <div class="col-sm-2">
    <section class="creat-task-section">
      <%= render 'form' %>
    </section>
  </div>

  <div class="col-sm-10">
    <section class="tasks-container">
        <%= form_tag tasks_path, method: :get, remote: true do |f| %>
          <div class="search_fm">
            <%= text_field_tag :q, params[:q], class: 'search' %>
            <%= select_tag :s, options_for_select([ "all statuses", "todo", "done"], params[:s] || "all statuses"), class: "search_sel"%>
            <%= select_tag :f, options_for_select([ "all dates", "expired", "not expired"], params[:f] || "all dates"), class: "search_sel"%>
            <%= date_field_tag :d, params[:d], id:"date_search"%>
            <%= select_tag :sorting, options_for_select([ "sorting none", "expire at asc", "expire at desc", "title asc", "title desc"],
                 params[:sorting] || "sorting none"), class: "search_sel"%>
            <%= submit_tag "Search", class: "btn btn-outline-success btn-sm", id: "search_btn" %>
          </div>
      <% end %>
    </section>
  </div>
</div>
<div id="task">
  <h2>Tasks</h2>
    <%= render partial: 'task', collection: @tasks %>
</div>
<div id="pages">
  <%= will_paginate @tasks %>
</div>

app/views/tasks/index.js.erb
document.querySelector('#task').innerHTML = "<%= j(render @tasks) %>";
bindTaskElem();